### ISSUE TITLE
Inferrence Problem: there is no bbox in output.

### ISSUE THREAD

**Issue by Changan00** [jefferyZhan/Griffon#20]
Hello, I encountered an issue while running inference with the Griffon-G model. Whether I use the query "Is there a motorcycle on the far left of the photo?" or "Detect all objects of the category set," the model's output is just a single paragraph without any numbers, and there is no image output. I have confirmed that my code runs without issues and that the model parameters are successfully loaded. Could you please help me understand what might be going wrong?

**Comment by jefferyZhan** [comment]
Unlike previous methods like early SPHINX, we do not limit the detection category set to the COCO categories. You need to specify the detailed categories in the category set like we have exampled in the paper like "Detect all objects of the category set. The category set includes [COCO 80 Categories]". Also, we also support flexible visual grounding, and you can also ask the model to locate several objects like "Locate the cars and the boys in the image". 
A clear intention is encouraged to be expressed in the instruction. For the query "Is there a motorcycle on the far left of the photo?", the model would like to answer with a textual description instead of returning the bbox.
